export const img1 = document.querySelector('.img1')
export const img2 = document.querySelector('.img2')
export const img3 = document.querySelector('.img3')
export const img4 = document.querySelector('.img4')
export const img5 = document.querySelector('.img5')
export const img6 = document.querySelector('.img6')
export const img7 = document.querySelector('.img7')
export const img11 = document.querySelector('.img11')
export const img22 = document.querySelector('.img22')
export const img33 = document.querySelector('.img33')
export const img44 = document.querySelector('.img44')
export const img55 = document.querySelector('.img55')
export const img66 = document.querySelector('.img66')
export const img77 = document.querySelector('.img77')

export const int1 = document.querySelector('.int1')
export const int2 = document.querySelector('.int2')
export const int3 = document.querySelector('.int3')
export const int4 = document.querySelector('.int4')
export const int5 = document.querySelector('.int5')
export const int6 = document.querySelector('.int6')
export const int7 = document.querySelector('.int7')
export const int11 = document.querySelector('.int11')
export const int22 = document.querySelector('.int22')
export const int33 = document.querySelector('.int33')
export const int44 = document.querySelector('.int44')
export const int55 = document.querySelector('.int55')
export const int66 = document.querySelector('.int66')
export const int77 = document.querySelector('.int77')

export const body = document.querySelector('main img')


